services:
  backend:
    image: 058264204819.dkr.ecr.eu-west-2.amazonaws.com/chattypatty-backend:latest
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

  frontend:
    image: 058264204819.dkr.ecr.eu-west-2.amazonaws.com/chattypatty-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
