"""add prompt to convo model

Revision ID: d130229e64e7
Revises: 3eb046db8dab
Create Date: 2025-07-18 17:43:15.224635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd130229e64e7'
down_revision: Union[str, Sequence[str], None] = '3eb046db8dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'prompt')
    # ### end Alembic commands ###
